### ISSUE TITLE
Issues with Ubuntu core

### ISSUE THREAD

**Issue by jose1711** [mtoensing/Moondance-StepMania64-pi4#2]
Tried this on Ubuntu core 64bit and RPi 3B+. After installing i3 wm and running the script I found two issues:
- `libglu1-mesa` package missing
- script assumes `pi` user, `ubuntu` is the default for Ubuntu (maybe use `~` instead of `/home/pi`?)

**Comment by mtoensing** [comment]
This script and tutorial is specifically for raspberry Pi OS.
