### ISSUE TITLE
Black screen with mouse cursor upon startup

### ISSUE THREAD

**Issue by dnwillia23** [mtoensing/Moondance-StepMania64-pi4#4]
Hello, thank you so much for putting this together.  I tried this out and everything works great.  The only problem is after the raspberry pi finishes booting up and then Stepmania autostarts, I get a black screen with just a mouse cursor in the middle.  I can hear the game's noises and can execute commands normally, but I can't see any of it taking place.  Are you aware of anything that might be causing this issue?

**Comment by dnwillia23** [comment]
My apologies, it looks like I posted too soon.  This was using the Raspberry Pi 64-bit OS from September 22, 2022: /raspios_arm64/images/raspios_arm64-2022-09-26/2022-09-22-raspios-bullseye-arm64.img.xz

I wiped my SD card and reimaged with the exact OS version you have listed in the README here.  Autostart is working without issue.

**Comment by mtoensing** [comment]
Glad to hear this. Happy to see people happy with some dancing during these times.
